// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9dVn5kRZwBfr-zLZAgZAUrZtKP4A8v0',
    appId: '1:829900922704:web:fca648f4ed993503f4d655',
    messagingSenderId: '829900922704',
    projectId: 'bdbarbearia-b91a2',
    authDomain: 'bdbarbearia-b91a2.firebaseapp.com',
    storageBucket: 'bdbarbearia-b91a2.firebasestorage.app',
    measurementId: 'G-4VRTCZFX93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2dbznE5PFC1XBs2HkkpeIOjCRLQQhBVw',
    appId: '1:829900922704:android:82d41e7ad9963421f4d655',
    messagingSenderId: '829900922704',
    projectId: 'bdbarbearia-b91a2',
    storageBucket: 'bdbarbearia-b91a2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO9dVn5kRZwBfr-zLZAgZAUrZtKP4A8v0',
    appId: '1:829900922704:web:cd4a5e663451af5bf4d655',
    messagingSenderId: '829900922704',
    projectId: 'bdbarbearia-b91a2',
    authDomain: 'bdbarbearia-b91a2.firebaseapp.com',
    storageBucket: 'bdbarbearia-b91a2.firebasestorage.app',
    measurementId: 'G-2JZYKBD7LY',
  );
}
